package com.ratanapps.notesapp.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single note record in the database.
 *
 * @property id Unique identifier for the note, auto-generated by Room.
 * @property notesTitle The title of the note.
 * @property notesContent The main body text of the note.
 * @property timeStamp The date and time when the note was created or last modified.
 */
@Entity(tableName = "notes_table")
data class NotesEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val notesTitle: String,
    val notesContent: String,
    val timeStamp: String
)
